app:
  name: "{{ .ProjectName }}"
  env:  "local"
  debug: true
  err_report: ""

database:
  default: "{{ .DBDrive }}"
{{- if (eq .DBDrive "mysql") }}
  mysql:
    dsn: ""

{{- else if (eq .DBDrive "postgre") }}
  postgre:
    dsn: ""

{{- else if (eq .DBDrive "clickhouse") }}
  clickhouse:
    dsn: ""

{{- end }}

queue:
  default: "{{ .QueueDrive }}"
{{- if (eq .QueueDrive "kafka") }}
  kafka:
    addr: ""

{{- else if (eq .QueueDrive "rabbitmq") }}
  rabbitmq:
    host: "127.0.0.1"
    port: "5672"
    vhost: "/"
    username: ""
    password: ""

{{- end}}

cache:
  default: "{{ .CacheDrive }}"
{{- if (eq .CacheDrive "redis") }}
  redis:
    host: "127.0.0.1"
    port: "6379"
    database: "0"
    auth: ""

{{- end}}

{{- if .IsTrace }}

trace:
  endpoint: ""

{{- end }}